services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NUXT_PUBLIC_API_BASE: ${NUXT_PUBLIC_API_BASE:-http://api-toi.daraedu.kz}
    restart: always
    ports:
      - "3030:3030"
