// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/13/2026, 12:23:36 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/yerkebulanabdilkakov/PythonProject/NewToi/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yerkebulanabdilkakov/PythonProject/NewToi/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yerkebulanabdilkakov/PythonProject/NewToi/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yerkebulanabdilkakov/PythonProject/NewToi/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yerkebulanabdilkakov/PythonProject/NewToi/frontend/plugins/**/*.{js,ts,mjs}","/Users/yerkebulanabdilkakov/PythonProject/NewToi/frontend/composables/**/*.{js,ts,mjs}","/Users/yerkebulanabdilkakov/PythonProject/NewToi/frontend/utils/**/*.{js,ts,mjs}","/Users/yerkebulanabdilkakov/PythonProject/NewToi/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yerkebulanabdilkakov/PythonProject/NewToi/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/yerkebulanabdilkakov/PythonProject/NewToi/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/yerkebulanabdilkakov/PythonProject/NewToi/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;