# Generated by Django 6.0.3 on 2026-03-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Тақырып")),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "excerpt",
                    models.TextField(blank=True, verbose_name="Қысқаша мазмұн"),
                ),
                ("content", models.TextField(verbose_name="Мазмұн")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/",
                        verbose_name="Мұқаба суреті",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Жарияланған"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Жарияланған күні"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Блог жазбасы",
                "verbose_name_plural": "Блог жазбалары",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
