# Generated by Django 6.0.3 on 2026-03-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SongCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категориялар",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Ән атауы")),
                (
                    "artist",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Орындаушы"
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, upload_to="songs/", verbose_name="Аудио файл"
                    ),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Сыртқы аудио URL (файл жүктеудің орнына)",
                        verbose_name="Аудио URL",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ұзақтығы секундпен",
                        verbose_name="Ұзақтығы (сек)",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="song_covers/",
                        verbose_name="Мұқаба суреті",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Белсенді"),
                ),
                (
                    "play_count",
                    models.PositiveIntegerField(default=0, verbose_name="Ойнату саны"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Реті")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="songs",
                        to="songs.songcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ән",
                "verbose_name_plural": "Әндер",
                "ordering": ["order", "title"],
            },
        ),
    ]
