# Generated by Django 6.0.3 on 2026-03-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("bride_name", models.CharField(max_length=255)),
                ("groom_name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("location", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True)),
                ("map_url", models.URLField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="invitations/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvitationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("uzatu", "Ұзату той"),
                            ("qyz_uzatu", "Қыз ұзату"),
                            ("sunnet", "Сүндет той"),
                            ("tusaukesar", "Тұсаукесер"),
                            ("merey", "Мерей той"),
                            ("besik", "Бесік той"),
                            ("betashar", "Беташар"),
                            ("other", "Асау тойлар"),
                        ],
                        default="uzatu",
                        max_length=32,
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(blank=True, null=True, upload_to="templates/"),
                ),
                ("gradient_from", models.CharField(default="#667eea", max_length=20)),
                ("gradient_to", models.CharField(default="#764ba2", max_length=20)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_free", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("yes", "Қатысады"),
                            ("no", "Қатыса алмайды"),
                            ("maybe", "Әлі ойлануда"),
                        ],
                        default="maybe",
                        max_length=32,
                    ),
                ),
                ("table_number", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="invitations.invitation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invitation",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invitations.invitationtemplate",
            ),
        ),
    ]
