# Generated by Django 6.0.3 on 2026-03-12 19:11

import re
import uuid

from django.db import migrations, models


def populate_template_slugs(apps, schema_editor):
    """Fill slug for any InvitationTemplate row that has none."""
    InvitationTemplate = apps.get_model('invitations', 'InvitationTemplate')
    for tmpl in InvitationTemplate.objects.filter(slug__isnull=True):
        base = re.sub(r'[^\w]+', '-', tmpl.name.lower()).strip('-') or 'template'
        slug = f'{base}-{uuid.uuid4().hex[:6]}'
        # Guard against accidental collision
        while InvitationTemplate.objects.filter(slug=slug).exists():
            slug = f'{base}-{uuid.uuid4().hex[:6]}'
        tmpl.slug = slug
        tmpl.save(update_fields=['slug'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0005_sample_template"),
    ]

    operations = [
        # 1. Remove the conditional UniqueConstraint we created manually
        migrations.RemoveConstraint(
            model_name="rsvpresponse",
            name="unique_rsvp_per_phone",
        ),
        # 2. Sync image_layout field (remove blank=True that was added in model)
        migrations.AlterField(
            model_name="invitation",
            name="image_layout",
            field=models.CharField(
                choices=[
                    ("gallery_top", "Gallery — Top"),
                    ("gallery_bottom", "Gallery — Bottom"),
                    ("gallery_grid", "2×N Grid"),
                    ("single_hero", "Single Hero Image"),
                ],
                default="gallery_top",
                max_length=50,
            ),
        ),
        # 3. Populate slugs before making the column NOT NULL
        migrations.RunPython(populate_template_slugs, noop),
        # 4. Now it's safe to mark slug as NOT NULL + unique
        migrations.AlterField(
            model_name="invitationtemplate",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        # 5. Replace UniqueConstraint with simpler unique_together
        migrations.AlterUniqueTogether(
            name="rsvpresponse",
            unique_together={("invitation", "phone")},
        ),
    ]
