# Generated by Django 6.0.3 on 2026-03-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0006_remove_rsvpresponse_unique_rsvp_per_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationtemplate",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
