# Generated by Django 6.0.3 on 2026-03-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0007_alter_invitationtemplate_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
