# Generated by Django 5.2.7 on 2026-03-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0013_add_owner_to_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
